#ifndef LADX_TESTS_BANK1_TEST_BANK1_H
#define LADX_TESTS_BANK1_TEST_BANK1_H

void test_prepare_entity_position_for_room_transition(void);
void test_update_recent_rooms_list(void);
void test_hide_all_sprites(void);
void test_hide_sprites(void);
void test_synchronize_dungeons_item_flags(void);
void test_create_following_npc_entity(void);
void test_func_001_6162(void);
void test_load_counter_animated_tiles(void);
void test_open_dungeon_name_dialog(void);
void test_load_tileset_0f_and_attributes(void);
void test_write_dma_code_to_hram(void);
void test_update_minimap_entrance_arrow(void);
void test_increment_gameplay_subtype(void);
void test_func_001_5888(void);
void test_initialize_inventory_bar(void);
void test_func_001_58A8(void);
void test_peach_picture_state_2(void);
void test_peach_picture_state_3(void);
void test_func_001_695B(void);
void test_func_6A7C(void);
void test_peach_picture_state_4(void);
void test_peach_picture_state_5_and_68D9(void);
void test_peach_picture_state_7(void);
void test_peach_picture_state_8(void);
void test_peach_picture_state_9(void);
void test_file_save_fade_out_and_state_A(void);
void test_peach_picture_state_0_and_1(void);
void test_peach_picture_entry_point(void);
void test_play_validation_jingle(void);
void test_func_001_5A59(void);
void test_world_map_states(void);
void test_move_select_and_jingle(void);
void test_label_001_5B3F(void);
void test_func_001_5A71(void);
void test_func_001_5C49_and_5C55(void);
void test_world_map_interactive_and_entry_point(void);
void test_build_save_slot_hearts_draw_command(void);
void test_func_5DC0_and_save_game_to_file(void);
void test_load_saved_file(void);
void test_func_001_4954(void);
void test_file_selection_interactive_and_choice(void);
void test_file_creation_init_and_sram(void);
void test_transition_to_file_menu_reload(void);
void test_file_creation_grid_and_entry(void);
void test_file_deletion_and_digits(void);
void test_file_deletion_interactive_and_erase(void);
void test_file_copy_subsystem(void);
void test_file_save_screen_and_init(void);
void test_game_over_subsystem(void);
void test_world_handler_subsystem(void);
void test_face_shrine_mural_subsystem(void);
void test_siren_instruments_subsystem(void);
void test_marin_beach_subsystem(void);
void test_intro_subsystem(void);

void run_bank1_tests(void);

#endif /* LADX_TESTS_BANK1_TEST_BANK1_H */
