#ifndef LADX_CONSTANTS_VFX_H
#define LADX_CONSTANTS_VFX_H

#include "common.h"

/* Values for wTranscientVfxTypeTable */
#define TRANSCIENT_VFX_NONE           0x00
#define TRANSCIENT_VFX_WATER_SPLASH   0x01
#define TRANSCIENT_VFX_POOF           0x02
#define TRANSCIENT_VFX_CHEST_APPEARS  0x03
#define TRANSCIENT_VFX_STAIRS_APPEARS 0x04
#define TRANSCIENT_VFX_SWORD_POKE     0x05
#define TRANSCIENT_VFX_LASER_BEAM     0x06
#define TRANSCIENT_VFX_MOVING_SPARKLE 0x07
#define TRANSCIENT_VFX_SMOKE          0x08
#define TRANSCIENT_VFX_RUMBLE         0x09
#define TRANSCIENT_VFX_LAVA_SPLASH    0x0A
#define TRANSCIENT_VFX_PEGASUS_DUST   0x0B
#define TRANSCIENT_VFX_PEGASUS_SPLASH 0x0C
#define TRANSCIENT_VFX_SWORD_BEAM     0x0D
#define TRANSCIENT_VFX_UNUSED_1       0x0E
#define TRANSCIENT_VFX_UNUSED_2       0x0F

#endif /* LADX_CONSTANTS_VFX_H */
